homeassistant:

  name: Dom
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  whitelist_external_dirs:
    - /config/www/cam_captures  
  customize: !include customize.yaml  
  packages: !include_dir_named packages    


default_config:

automation:  !include automations.yaml 
zone: !include zones.yaml
frontend:
  themes: !include themes.yaml


ffmpeg:

device_tracker:
  - platform: bluetooth_le_tracker
  

mobile_app:
      
python_script:  

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret tts_url
    service_name: google_say
    

    
    
wake_on_lan:      

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret aqara_gateway_key
    
    
    
webostv:
  host: !secret webos_tv_ip
  customize:
    sources:
      - livetv
      - youtube
      - makotv
      - netflix
      - Cyfrowy Polsat
      - Spotify - Muzyka i podcasty
      - HBO GO
      - Player    
      
      
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password      
  
  
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_chat_1
      - !secret telegram_chat_2
              